# ecosystem.config.yaml
apps:
  - name: NeteaseCloudMusicApi
    script: ./netease-music-api/server.js
    instances: 1
    exec_mode: fork
    watch: false
    max_memory_restart: 200M

  - name: bilibili-openStation
    script: ./bilibili-open-api/server.js
    instances: 1
    exec_mode: fork
    watch: false
    max_memory_restart: 100M


  - name: bilibili-ordersong-plugin
    script: ./app.js
    instances: 1
    exec_mode: fork
    watch: false
    max_memory_restart: 100M